### ISSUE TITLE
"efficiency" is seldom easy

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/ds-pipelines-1-course#55]
> Lastly, imagine the following comment appeared on your pull request.

> Oh shoot @aappling-usgs, I am using your results for FANCY BIG PROJECT and I have coded everything to assume your outputs use the convention "PB", "DL", and "PGDL" (instead of lowercase). Can you update your code accordingly?

> Would your code be easy to adjust to satisfy this request? Would you need to re-run any steps that aren't associated with this naming choice?

I tried this. It sounds cool, but it's for the best that it's optional, because every function requires find-replace operations in the code to change the capitalization (the .csv file of course, but also the .tsv and .png files).

**Comment by jordansread** [comment]
Agreed. I created this example before I really thought it through. Ideally we'd have a few things here: 1) a download or processing step that takes a long time, 2) a minor change to a later step that takes a lot less time, and is simple to implement. 

I don't want to make it as trivial as changing the dimensions of a plot, since they wouldn't see why it is important to separate the targets in that case (vs running the bottom of a spaghetti script)

**Comment by aappling-usgs** [comment]
Yeah, it's hard to come up with something truly perfect. At first glance this one seemed perfect, so I think they'll get the idea anyway. Could also harden the downstream code for this example so that it's robust to changes in capitalization.
